### PR TITLE
chore: change version number to support LiteXL 2.1

### PR DESCRIPTION
**Pull request by benstigsen**
This makes `litepresence` work for LiteXL V2.1.

### CODE REVIEW

**Comment by sammy-ette** [comment]
thank u but can u make commit and title conventional (look at commit history)

**Comment by benstigsen** [comment]
Sure, but I'm not actually quite sure what this counts as.
`fix` or `chore` ?

**Comment by sammy-ette** [comment]
it would be chore

**Comment by benstigsen** [comment]
Should be good now.

**Comment by sammy-ette** [comment]
thanks github for not giving me a notification
the takase commit being here is a bit odd but its fine

**Pull request merged**
